---
title: "Lab04_Pan"
format: pdf
editor: visual
---

```{r}
#Carregando os pacotes
library(readxl)
library(tidyverse)
```

```{r}
#Caminho do arquivo
fname <- "C:\\Users\\artur\\Documents\\curso r\\WDIEXCEL.xlsx"
file.exists(fname)
```

```{r}
#Leitura dos países
countries_cru <- read_xlsx(fname, sheet = "Country")
countries <- countries_cru[c(30, 21, 3, 39, 14), ]

#Seleção dos dados desejados
WDI_cru <- read_xlsx(fname, sheet = "Data")
WDI <- WDI_cru[, c(2, 4:63)]
```

```{r}
#WDI não está em formato tidy pois cada ano é uma coluna
library(tidyr)
#Transformando WDI em tidy
WDI <- pivot_longer(WDI,
                    cols = c(3:61),
                    names_to = "YEAR")
WDI$YEAR <- as.integer(WDI$YEAR)
```

```{r}
# Tratamento e seleção das colunas desejadas

library(dplyr)
WDI <- WDI %>%
  filter(`Indicator Code` == "SP.DYN.CBRT.IN") %>%
  inner_join(countries %>% select(`Country Code`, `Short Name`), by = "Country Code") %>%
  rename(SP.DYN.CBRT.IN = value) %>%
  select(`Country Code`, `Short Name`, YEAR, SP.DYN.CBRT.IN)

#Ordenar por país e ano
WDI <- WDI %>%
  arrange(`Country Code`, YEAR)
```

```{r}
#Gráfico
library(ggplot2)
ggplot(WDI, aes(x = YEAR, y = SP.DYN.CBRT.IN, color = `Short Name`)) +
  geom_line(linewidth = 1) +
  labs(
    title = "Taxa Bruta de Natalidade por País",
    x = "Ano (YEAR)",
    y = "SP.DYN.CBRT.IN",
    color = "País"
  ) +
  theme_minimal()
```

```{r}
#Horário da compilação
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```

